version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: striptags
    versions:
    - ">= 0"
  - dependency-name: textlint-rule-preset-japanese
    versions:
    - 6.0.0
  - dependency-name: gatsby-remark-responsive-iframe
    versions:
    - 2.10.0
    - 2.11.0
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 4.0.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: textlint
    versions:
    - 11.8.1
    - 11.8.2
    - 11.8.3
  - dependency-name: gatsby-source-filesystem
    versions:
    - 3.0.0
  - dependency-name: devicon
    versions:
    - 2.10.0
    - 2.10.1
  - dependency-name: react-lazyload
    versions:
    - 3.1.1
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
